---
title: "R Notebook"
output: html_notebook
---

Objective: Test collabration potential of github using a simple example.

task:
use any data to create or modify ggplot graphs in a shared notebook (this notebook)



first shot:
```{r message=FALSE, warning=FALSE}
library(tidyverse)

data(mtcars) #yes, I know, not very origianal


mtcars %>% 
  mutate(model = rownames(.), gear = as.factor(gear), model = as.factor(model)) %>% 
  select(model, everything()) %>% 
  arrange(model) %>% 
  mutate(model = forcats::fct_rev(model)) %>% 
  ggplot(aes(x = model, y = mpg, fill = gear))+
  geom_bar(stat = "identity", color = "black")+
  coord_flip() 

```

Ben's Code
```{r}
starwars %>% 
  filter(species %in% c("Human", "Droid") & is.finite(mass)) %>% 
  ggplot()+
  geom_boxplot(aes(x=species,y=mass))+
  xlab("Species")+
  ylab("Mass (kg)")

# this comment is a test
```

It sounds like we could revert back to a previous version at any time, I'll have to play around with how that would be done.

Looks like a happy primer:
http://r-bio.github.io/intro-git-rstudio/


```{r}
starwars %>% #cool set
select(species, films) %>% 
filter(!is.na(species)) %>% 
mutate(n_films = lengths(films))  %>% 
mutate(species = forcats::fct_rev(species)) %>% 
ggplot(aes(x = species, y = n_films))+
geom_bar(stat = "identity", fill = "lightblue") +
coord_flip()
```





















